spring:
  application:
    name: ticket
  datasource:
    url: jdbc:mysql://localhost:3306/coupon?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create