spring:
  application:
    name: ticket
  datasource:
    url: jdbc:h2:tcp://localhost/~/coupon-test
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false