spring:
  application:
    name: coupon
  datasource:
    url: jdbc:h2:tcp://localhost/~/coupon
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true